# ===============================
# CONFIGURATION SERVEUR
# ===============================
spring.application.name=predict-backend
server.port=8080

# ===============================
# CONFIGURATION BASE DE DONNEES (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/attijari_predict_db?serverTimezone=UTC&useSSL=false&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / Dialect (évite d'avoir besoin de métadonnées JDBC au démarrage)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# HikariCP : évite de tuer l'app si MySQL n'est pas prêt au tout début
spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

# ===============================
# CONFIGURATION HIBERNATE / JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ===============================
# CONFIGURATION EMAIL (GMAIL SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.username=filaliomar070@gmail.com
spring.mail.password=vysu nlut dvpg bpxa
spring.mail.properties.mail.smtp.auth=true

# ===============================
# BATCH NOCTURNE (nightly_batch.py)
# ===============================
ai.engine.python.path=/Users/omarfilali/Desktop/AWB/moteur-ia-python/venv/bin/python3
ai.engine.script.path=/Users/omarfilali/Desktop/AWB/moteur-ia-python/nightly_batch.py
ai.engine.working.dir=/Users/omarfilali/Desktop/AWB/moteur-ia-python



# ===============================
# KEYCLOAK — OAuth2 Resource Server
# ===============================
# Spring Boot appellera http://localhost:8081/realms/digitalbank-realm/.well-known/openid-configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/digitalbank-realm

# ===============================
# DEBUG SECURITÉ
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
# ===============================
# CONFIGURATION JACKSON / JSON
# ===============================
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd

